// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package usecase

import (
	"database/sql"
	"github.com/sandonemaki/my_read_memo_Go_API/backend/core/infra/query"
	"github.com/sandonemaki/my_read_memo_Go_API/backend/core/infra/repository"
	"github.com/sandonemaki/my_read_memo_Go_API/backend/pkg/db"
)

// Injectors from wire.go:

func NewUserDI(sqlDB *sql.DB) User {
	client := db.NewDB(sqlDB)
	queryUser := query.NewUser(client)
	repositoryUser := repository.NewUser(client)
	usecaseUser := NewUser(queryUser, repositoryUser)
	return usecaseUser
}
