services:
  testdb:
    image: postgres:15-alpine
    container_name: yondeco_testdb
    networks:
      - yondeco_net
    environment:
      POSTGRES_USER: yondeco
      POSTGRES_PASSWORD: yondeco
      POSTGRES_DB: testdb
      TZ: "Asia/Tokyo"
    ports:
      - "5433:5432"
    volumes:
      - testdb_data:/var/lib/postgresql/data
  db:
    image: postgres:15-alpine
    container_name: yondeco_db
    networks:
      - yondeco_net
    environment:
      POSTGRES_USER: yondeco
      POSTGRES_PASSWORD: yondeco
      POSTGRES_DB: yondeco
      TZ: "Asia/Tokyo"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  yondeco_net:
    driver: bridge

volumes:
  testdb_data:
  db_data:
