env:
  name: "test"

dev:
  http:
    cors: ["https://*", "http://*"]
    port: 8080
  logger:
    debug: true
  postgres:
    dbname: "yondeco"
    host: "localhost"
    port: "5432"
    user: "yondeco"
    pass: "yondeco"
    sslmode: "disable"

test:
  http:
    cors: ["https://*", "http://*"]
    port: 8080
  logger:
    debug: true
  postgres:
    dbname: "testdb"
    host: "localhost"
    port: "5433"
    user: "yondeco"
    pass: "yondeco"
    sslmode: "disable"
