env:
  name: "test"

dev:
  http:
    cors: ["https://*", "http://*"]
    port: 8080
  logger:
    debug: false
  postgres:
    dbname: :"yondeco"
    host: "localhost"
    port: 5432
    user: :"yondeco"
    password: :"yondeco"
    sslmode: "disable"

test:
  http:
    cors: ["https://*", "http://*"]
    port: 8080
  logger:
    debug: false
  postgres:
    dbname: :"yondeco_test"
    host: "localhost"
    port: 5432
    user: "yondeco_test"
    password: "yondeco_test"
    sslmode: "disable"
