// Code generated by BobGen psql v0.38.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodels_test

import (
	models "github.com/sandonemaki/my_read_memo_Go_API/backend/pkg/dbmodels"
	"github.com/stephenafamo/bob"
)

// Set the testDB to enable tests that use the database
var testDB bob.Transactor

// Make sure the type Author runs hooks after queries
var _ bob.HookableType = &models.Author{}

// Make sure the type GooseDBVersion runs hooks after queries
var _ bob.HookableType = &models.GooseDBVersion{}

// Make sure the type KindleHighlight runs hooks after queries
var _ bob.HookableType = &models.KindleHighlight{}

// Make sure the type MasterBook runs hooks after queries
var _ bob.HookableType = &models.MasterBook{}

// Make sure the type OcrText runs hooks after queries
var _ bob.HookableType = &models.OcrText{}

// Make sure the type Publisher runs hooks after queries
var _ bob.HookableType = &models.Publisher{}

// Make sure the type RandokuImage runs hooks after queries
var _ bob.HookableType = &models.RandokuImage{}

// Make sure the type RandokuMemo runs hooks after queries
var _ bob.HookableType = &models.RandokuMemo{}

// Make sure the type ReadingHistory runs hooks after queries
var _ bob.HookableType = &models.ReadingHistory{}

// Make sure the type SeidokuMemo runs hooks after queries
var _ bob.HookableType = &models.SeidokuMemo{}

// Make sure the type UserBookLog runs hooks after queries
var _ bob.HookableType = &models.UserBookLog{}

// Make sure the type User runs hooks after queries
var _ bob.HookableType = &models.User{}
