// Code generated by BobGen psql v0.38.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodels

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// Publisher is an object representing the database table.
type Publisher struct {
	ID        int64     `db:"id,pk" `
	Name      string    `db:"name" `
	CreatedAt time.Time `db:"created_at" `
	UpdatedAt time.Time `db:"updated_at" `

	R publisherR `db:"-" `
}

// PublisherSlice is an alias for a slice of pointers to Publisher.
// This should almost always be used instead of []*Publisher.
type PublisherSlice []*Publisher

// Publishers contains methods to work with the publishers table
var Publishers = psql.NewTablex[*Publisher, PublisherSlice, *PublisherSetter]("", "publishers")

// PublishersQuery is a query on the publishers table
type PublishersQuery = *psql.ViewQuery[*Publisher, PublisherSlice]

// publisherR is where relationships are stored.
type publisherR struct {
	MasterBooks MasterBookSlice // master_books.master_books_publisher_id_fkey
}

type publisherColumnNames struct {
	ID        string
	Name      string
	CreatedAt string
	UpdatedAt string
}

var PublisherColumns = buildPublisherColumns("publishers")

type publisherColumns struct {
	tableAlias string
	ID         psql.Expression
	Name       psql.Expression
	CreatedAt  psql.Expression
	UpdatedAt  psql.Expression
}

func (c publisherColumns) Alias() string {
	return c.tableAlias
}

func (publisherColumns) AliasedAs(alias string) publisherColumns {
	return buildPublisherColumns(alias)
}

func buildPublisherColumns(alias string) publisherColumns {
	return publisherColumns{
		tableAlias: alias,
		ID:         psql.Quote(alias, "id"),
		Name:       psql.Quote(alias, "name"),
		CreatedAt:  psql.Quote(alias, "created_at"),
		UpdatedAt:  psql.Quote(alias, "updated_at"),
	}
}

type publisherWhere[Q psql.Filterable] struct {
	ID        psql.WhereMod[Q, int64]
	Name      psql.WhereMod[Q, string]
	CreatedAt psql.WhereMod[Q, time.Time]
	UpdatedAt psql.WhereMod[Q, time.Time]
}

func (publisherWhere[Q]) AliasedAs(alias string) publisherWhere[Q] {
	return buildPublisherWhere[Q](buildPublisherColumns(alias))
}

func buildPublisherWhere[Q psql.Filterable](cols publisherColumns) publisherWhere[Q] {
	return publisherWhere[Q]{
		ID:        psql.Where[Q, int64](cols.ID),
		Name:      psql.Where[Q, string](cols.Name),
		CreatedAt: psql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt: psql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

var PublisherErrors = &publisherErrors{
	ErrUniquePublishersPkey: &UniqueConstraintError{
		schema:  "",
		table:   "publishers",
		columns: []string{"id"},
		s:       "publishers_pkey",
	},
}

type publisherErrors struct {
	ErrUniquePublishersPkey *UniqueConstraintError
}

// PublisherSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type PublisherSetter struct {
	ID        *int64     `db:"id,pk" `
	Name      *string    `db:"name" `
	CreatedAt *time.Time `db:"created_at" `
	UpdatedAt *time.Time `db:"updated_at" `
}

func (s PublisherSetter) SetColumns() []string {
	vals := make([]string, 0, 4)
	if s.ID != nil {
		vals = append(vals, "id")
	}

	if s.Name != nil {
		vals = append(vals, "name")
	}

	if s.CreatedAt != nil {
		vals = append(vals, "created_at")
	}

	if s.UpdatedAt != nil {
		vals = append(vals, "updated_at")
	}

	return vals
}

func (s PublisherSetter) Overwrite(t *Publisher) {
	if s.ID != nil {
		t.ID = *s.ID
	}
	if s.Name != nil {
		t.Name = *s.Name
	}
	if s.CreatedAt != nil {
		t.CreatedAt = *s.CreatedAt
	}
	if s.UpdatedAt != nil {
		t.UpdatedAt = *s.UpdatedAt
	}
}

func (s *PublisherSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Publishers.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 4)
		if s.ID != nil {
			vals[0] = psql.Arg(*s.ID)
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.Name != nil {
			vals[1] = psql.Arg(*s.Name)
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt != nil {
			vals[2] = psql.Arg(*s.CreatedAt)
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt != nil {
			vals[3] = psql.Arg(*s.UpdatedAt)
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s PublisherSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s PublisherSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 4)

	if s.ID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.Name != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	if s.CreatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindPublisher retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindPublisher(ctx context.Context, exec bob.Executor, IDPK int64, cols ...string) (*Publisher, error) {
	if len(cols) == 0 {
		return Publishers.Query(
			SelectWhere.Publishers.ID.EQ(IDPK),
		).One(ctx, exec)
	}

	return Publishers.Query(
		SelectWhere.Publishers.ID.EQ(IDPK),
		sm.Columns(Publishers.Columns().Only(cols...)),
	).One(ctx, exec)
}

// PublisherExists checks the presence of a single record by primary key
func PublisherExists(ctx context.Context, exec bob.Executor, IDPK int64) (bool, error) {
	return Publishers.Query(
		SelectWhere.Publishers.ID.EQ(IDPK),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Publisher is retrieved from the database
func (o *Publisher) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Publishers.AfterSelectHooks.RunHooks(ctx, exec, PublisherSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Publishers.AfterInsertHooks.RunHooks(ctx, exec, PublisherSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Publishers.AfterUpdateHooks.RunHooks(ctx, exec, PublisherSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Publishers.AfterDeleteHooks.RunHooks(ctx, exec, PublisherSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Publisher
func (o *Publisher) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Publisher) pkEQ() dialect.Expression {
	return psql.Quote("publishers", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Publisher
func (o *Publisher) Update(ctx context.Context, exec bob.Executor, s *PublisherSetter) error {
	v, err := Publishers.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Publisher record with an executor
func (o *Publisher) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Publishers.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Publisher using the executor
func (o *Publisher) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Publishers.Query(
		SelectWhere.Publishers.ID.EQ(o.ID),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after PublisherSlice is retrieved from the database
func (o PublisherSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Publishers.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Publishers.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Publishers.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Publishers.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o PublisherSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("publishers", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o PublisherSlice) copyMatchingRows(from ...*Publisher) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o PublisherSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Publishers.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Publisher:
				o.copyMatchingRows(retrieved)
			case []*Publisher:
				o.copyMatchingRows(retrieved...)
			case PublisherSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Publisher or a slice of Publisher
				// then run the AfterUpdateHooks on the slice
				_, err = Publishers.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o PublisherSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Publishers.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Publisher:
				o.copyMatchingRows(retrieved)
			case []*Publisher:
				o.copyMatchingRows(retrieved...)
			case PublisherSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Publisher or a slice of Publisher
				// then run the AfterDeleteHooks on the slice
				_, err = Publishers.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o PublisherSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals PublisherSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Publishers.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o PublisherSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Publishers.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o PublisherSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Publishers.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type publisherJoins[Q dialect.Joinable] struct {
	typ         string
	MasterBooks modAs[Q, masterBookColumns]
}

func (j publisherJoins[Q]) aliasedAs(alias string) publisherJoins[Q] {
	return buildPublisherJoins[Q](buildPublisherColumns(alias), j.typ)
}

func buildPublisherJoins[Q dialect.Joinable](cols publisherColumns, typ string) publisherJoins[Q] {
	return publisherJoins[Q]{
		typ: typ,
		MasterBooks: modAs[Q, masterBookColumns]{
			c: MasterBookColumns,
			f: func(to masterBookColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, MasterBooks.Name().As(to.Alias())).On(
						to.PublisherID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}

// MasterBooks starts a query for related objects on master_books
func (o *Publisher) MasterBooks(mods ...bob.Mod[*dialect.SelectQuery]) MasterBooksQuery {
	return MasterBooks.Query(append(mods,
		sm.Where(MasterBookColumns.PublisherID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os PublisherSlice) MasterBooks(mods ...bob.Mod[*dialect.SelectQuery]) MasterBooksQuery {
	pkID := make(pgtypes.Array[int64], len(os))
	for i, o := range os {
		pkID[i] = o.ID
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "bigint[]")),
	))

	return MasterBooks.Query(append(mods,
		sm.Where(psql.Group(MasterBookColumns.PublisherID).OP("IN", PKArgExpr)),
	)...)
}

func (o *Publisher) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "MasterBooks":
		rels, ok := retrieved.(MasterBookSlice)
		if !ok {
			return fmt.Errorf("publisher cannot load %T as %q", retrieved, name)
		}

		o.R.MasterBooks = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Publisher = o
			}
		}
		return nil
	default:
		return fmt.Errorf("publisher has no relationship %q", name)
	}
}

type publisherPreloader struct{}

func buildPublisherPreloader() publisherPreloader {
	return publisherPreloader{}
}

type publisherThenLoader[Q orm.Loadable] struct {
	MasterBooks func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildPublisherThenLoader[Q orm.Loadable]() publisherThenLoader[Q] {
	type MasterBooksLoadInterface interface {
		LoadMasterBooks(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return publisherThenLoader[Q]{
		MasterBooks: thenLoadBuilder[Q](
			"MasterBooks",
			func(ctx context.Context, exec bob.Executor, retrieved MasterBooksLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadMasterBooks(ctx, exec, mods...)
			},
		),
	}
}

// LoadMasterBooks loads the publisher's MasterBooks into the .R struct
func (o *Publisher) LoadMasterBooks(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.MasterBooks = nil

	related, err := o.MasterBooks(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Publisher = o
	}

	o.R.MasterBooks = related
	return nil
}

// LoadMasterBooks loads the publisher's MasterBooks into the .R struct
func (os PublisherSlice) LoadMasterBooks(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	masterBooks, err := os.MasterBooks(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		o.R.MasterBooks = nil
	}

	for _, o := range os {
		for _, rel := range masterBooks {
			if o.ID != rel.PublisherID {
				continue
			}

			rel.R.Publisher = o

			o.R.MasterBooks = append(o.R.MasterBooks, rel)
		}
	}

	return nil
}

func insertPublisherMasterBooks0(ctx context.Context, exec bob.Executor, masterBooks1 []*MasterBookSetter, publisher0 *Publisher) (MasterBookSlice, error) {
	for i := range masterBooks1 {
		masterBooks1[i].PublisherID = &publisher0.ID
	}

	ret, err := MasterBooks.Insert(bob.ToMods(masterBooks1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertPublisherMasterBooks0: %w", err)
	}

	return ret, nil
}

func attachPublisherMasterBooks0(ctx context.Context, exec bob.Executor, count int, masterBooks1 MasterBookSlice, publisher0 *Publisher) (MasterBookSlice, error) {
	setter := &MasterBookSetter{
		PublisherID: &publisher0.ID,
	}

	err := masterBooks1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachPublisherMasterBooks0: %w", err)
	}

	return masterBooks1, nil
}

func (publisher0 *Publisher) InsertMasterBooks(ctx context.Context, exec bob.Executor, related ...*MasterBookSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	masterBooks1, err := insertPublisherMasterBooks0(ctx, exec, related, publisher0)
	if err != nil {
		return err
	}

	publisher0.R.MasterBooks = append(publisher0.R.MasterBooks, masterBooks1...)

	for _, rel := range masterBooks1 {
		rel.R.Publisher = publisher0
	}
	return nil
}

func (publisher0 *Publisher) AttachMasterBooks(ctx context.Context, exec bob.Executor, related ...*MasterBook) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	masterBooks1 := MasterBookSlice(related)

	_, err = attachPublisherMasterBooks0(ctx, exec, len(related), masterBooks1, publisher0)
	if err != nil {
		return err
	}

	publisher0.R.MasterBooks = append(publisher0.R.MasterBooks, masterBooks1...)

	for _, rel := range related {
		rel.R.Publisher = publisher0
	}

	return nil
}
