// Code generated by BobGen psql v0.38.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodels_test

import (
	"context"
	"errors"
	"testing"

	models "github.com/sandonemaki/my_read_memo_Go_API/backend/pkg/dbmodels"
	factory "github.com/sandonemaki/my_read_memo_Go_API/backend/pkg/dbmodels/factory"
	"github.com/stephenafamo/bob"
)

func TestUserBookLogUniqueConstraintErrors(t *testing.T) {
	if testDB == nil {
		t.Skip("No database connection provided")
	}

	f := factory.New()
	tests := []struct {
		name         string
		expectedErr  *models.UniqueConstraintError
		conflictMods func(context.Context, bob.Executor, *models.UserBookLog) factory.UserBookLogModSlice
	}{
		{
			name:        "ErrUniqueUserBookLogsPkey",
			expectedErr: models.UserBookLogErrors.ErrUniqueUserBookLogsPkey,
			conflictMods: func(ctx context.Context, exec bob.Executor, obj *models.UserBookLog) factory.UserBookLogModSlice {
				shouldUpdate := false
				updateMods := make(factory.UserBookLogModSlice, 0, 1)

				if shouldUpdate {
					if err := obj.Update(ctx, exec, f.NewUserBookLog(ctx, updateMods...).BuildSetter()); err != nil {
						t.Fatalf("Error updating object: %v", err)
					}
				}

				return factory.UserBookLogModSlice{
					factory.UserBookLogMods.ID(obj.ID),
				}
			},
		},
		{
			name:        "ErrUniqueUserBookLogsUserUlidMasterBookIdKey",
			expectedErr: models.UserBookLogErrors.ErrUniqueUserBookLogsUserUlidMasterBookIdKey,
			conflictMods: func(ctx context.Context, exec bob.Executor, obj *models.UserBookLog) factory.UserBookLogModSlice {
				shouldUpdate := false
				updateMods := make(factory.UserBookLogModSlice, 0, 2)

				if shouldUpdate {
					if err := obj.Update(ctx, exec, f.NewUserBookLog(ctx, updateMods...).BuildSetter()); err != nil {
						t.Fatalf("Error updating object: %v", err)
					}
				}

				return factory.UserBookLogModSlice{
					factory.UserBookLogMods.UserUlid(obj.UserUlid),
					factory.UserBookLogMods.MasterBookID(obj.MasterBookID),
				}
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			ctx, cancel := context.WithCancel(context.Background())
			t.Cleanup(cancel)

			tx, err := testDB.Begin(ctx)
			if err != nil {
				t.Fatalf("Couldn't start database transaction: %v", err)
			}

			defer func() {
				if err := tx.Rollback(ctx); err != nil {
					t.Fatalf("Error rolling back transaction: %v", err)
				}
			}()

			var exec bob.Executor = tx

			obj, err := f.NewUserBookLog(ctx, factory.UserBookLogMods.WithParentsCascading()).Create(ctx, exec)
			if err != nil {
				t.Fatal(err)
			}

			obj2, err := f.NewUserBookLog(ctx).Create(ctx, exec)
			if err != nil {
				t.Fatal(err)
			}

			err = obj2.Update(ctx, exec, f.NewUserBookLog(ctx, tt.conflictMods(ctx, exec, obj)...).BuildSetter())
			if !errors.Is(models.ErrUniqueConstraint, err) {
				t.Fatalf("Expected: %s, Got: %v", tt.name, err)
			}
			if !errors.Is(tt.expectedErr, err) {
				t.Fatalf("Expected: %s, Got: %v", tt.expectedErr.Error(), err)
			}
			if !models.ErrUniqueConstraint.Is(err) {
				t.Fatalf("Expected: %s, Got: %v", tt.name, err)
			}
			if !tt.expectedErr.Is(err) {
				t.Fatalf("Expected: %s, Got: %v", tt.expectedErr.Error(), err)
			}
		})
	}
}
