// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"github.com/sandonemaki/my_read_memo_Go_API/backend/core/infra/query"
	"github.com/sandonemaki/my_read_memo_Go_API/backend/core/infra/repository"
	"github.com/sandonemaki/my_read_memo_Go_API/backend/core/usecase"
	"github.com/sandonemaki/my_read_memo_Go_API/backend/pkg/config"
	"github.com/sandonemaki/my_read_memo_Go_API/backend/pkg/db"
	"github.com/sandonemaki/my_read_memo_Go_API/backend/pkg/logger"
	"log/slog"
)

// Injectors from wire.go:

func NewUserUseCase(configLogger config.Logger, postgres config.Postgres, string2 string) usecase.User {
	handler := logger.NewLogger(configLogger)
	slogLogger := slog.New(handler)
	sqlDB := db.NewPSQL(postgres, slogLogger, string2)
	client := db.NewDB(sqlDB)
	user := query.NewUser(client)
	repositoryUser := repository.NewUser(client)
	usecaseUser := usecase.NewUser(user, repositoryUser)
	return usecaseUser
}
