/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Yondeco
 * OpenAPI spec version: 1.0.0-oas3.0.3
 */
import type { User } from "./user";

export interface UserResponse {
	user: User;
}
