// Code generated by BobGen psql v0.34.2. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
)

// RandokuMemo is an object representing the database table.
type RandokuMemo struct {
	ID           int64           `db:"id,pk" `
	Content      string          `db:"content" `
	ContentState int32           `db:"content_state" `
	BookID       null.Val[int64] `db:"book_id" `
	CreatedAt    time.Time       `db:"created_at" `
	UpdatedAt    time.Time       `db:"updated_at" `

	R randokuMemoR `db:"-" `
}

// RandokuMemoSlice is an alias for a slice of pointers to RandokuMemo.
// This should almost always be used instead of []*RandokuMemo.
type RandokuMemoSlice []*RandokuMemo

// RandokuMemos contains methods to work with the randoku_memos table
var RandokuMemos = psql.NewTablex[*RandokuMemo, RandokuMemoSlice, *RandokuMemoSetter]("", "randoku_memos")

// RandokuMemosQuery is a query on the randoku_memos table
type RandokuMemosQuery = *psql.ViewQuery[*RandokuMemo, RandokuMemoSlice]

// randokuMemoR is where relationships are stored.
type randokuMemoR struct {
	Book *Book // randoku_memos.randoku_memos_book_id_fkey
}

type randokuMemoColumnNames struct {
	ID           string
	Content      string
	ContentState string
	BookID       string
	CreatedAt    string
	UpdatedAt    string
}

var RandokuMemoColumns = buildRandokuMemoColumns("randoku_memos")

type randokuMemoColumns struct {
	tableAlias   string
	ID           psql.Expression
	Content      psql.Expression
	ContentState psql.Expression
	BookID       psql.Expression
	CreatedAt    psql.Expression
	UpdatedAt    psql.Expression
}

func (c randokuMemoColumns) Alias() string {
	return c.tableAlias
}

func (randokuMemoColumns) AliasedAs(alias string) randokuMemoColumns {
	return buildRandokuMemoColumns(alias)
}

func buildRandokuMemoColumns(alias string) randokuMemoColumns {
	return randokuMemoColumns{
		tableAlias:   alias,
		ID:           psql.Quote(alias, "id"),
		Content:      psql.Quote(alias, "content"),
		ContentState: psql.Quote(alias, "content_state"),
		BookID:       psql.Quote(alias, "book_id"),
		CreatedAt:    psql.Quote(alias, "created_at"),
		UpdatedAt:    psql.Quote(alias, "updated_at"),
	}
}

type randokuMemoWhere[Q psql.Filterable] struct {
	ID           psql.WhereMod[Q, int64]
	Content      psql.WhereMod[Q, string]
	ContentState psql.WhereMod[Q, int32]
	BookID       psql.WhereNullMod[Q, int64]
	CreatedAt    psql.WhereMod[Q, time.Time]
	UpdatedAt    psql.WhereMod[Q, time.Time]
}

func (randokuMemoWhere[Q]) AliasedAs(alias string) randokuMemoWhere[Q] {
	return buildRandokuMemoWhere[Q](buildRandokuMemoColumns(alias))
}

func buildRandokuMemoWhere[Q psql.Filterable](cols randokuMemoColumns) randokuMemoWhere[Q] {
	return randokuMemoWhere[Q]{
		ID:           psql.Where[Q, int64](cols.ID),
		Content:      psql.Where[Q, string](cols.Content),
		ContentState: psql.Where[Q, int32](cols.ContentState),
		BookID:       psql.WhereNull[Q, int64](cols.BookID),
		CreatedAt:    psql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:    psql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

var RandokuMemoErrors = &randokuMemoErrors{
	ErrUniqueRandokuMemosPkey: &UniqueConstraintError{s: "randoku_memos_pkey"},
}

type randokuMemoErrors struct {
	ErrUniqueRandokuMemosPkey *UniqueConstraintError
}

// RandokuMemoSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type RandokuMemoSetter struct {
	ID           omit.Val[int64]     `db:"id,pk" `
	Content      omit.Val[string]    `db:"content" `
	ContentState omit.Val[int32]     `db:"content_state" `
	BookID       omitnull.Val[int64] `db:"book_id" `
	CreatedAt    omit.Val[time.Time] `db:"created_at" `
	UpdatedAt    omit.Val[time.Time] `db:"updated_at" `
}

func (s RandokuMemoSetter) SetColumns() []string {
	vals := make([]string, 0, 6)
	if !s.ID.IsUnset() {
		vals = append(vals, "id")
	}

	if !s.Content.IsUnset() {
		vals = append(vals, "content")
	}

	if !s.ContentState.IsUnset() {
		vals = append(vals, "content_state")
	}

	if !s.BookID.IsUnset() {
		vals = append(vals, "book_id")
	}

	if !s.CreatedAt.IsUnset() {
		vals = append(vals, "created_at")
	}

	if !s.UpdatedAt.IsUnset() {
		vals = append(vals, "updated_at")
	}

	return vals
}

func (s RandokuMemoSetter) Overwrite(t *RandokuMemo) {
	if !s.ID.IsUnset() {
		t.ID, _ = s.ID.Get()
	}
	if !s.Content.IsUnset() {
		t.Content, _ = s.Content.Get()
	}
	if !s.ContentState.IsUnset() {
		t.ContentState, _ = s.ContentState.Get()
	}
	if !s.BookID.IsUnset() {
		t.BookID, _ = s.BookID.GetNull()
	}
	if !s.CreatedAt.IsUnset() {
		t.CreatedAt, _ = s.CreatedAt.Get()
	}
	if !s.UpdatedAt.IsUnset() {
		t.UpdatedAt, _ = s.UpdatedAt.Get()
	}
}

func (s *RandokuMemoSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return RandokuMemos.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 6)
		if s.ID.IsUnset() {
			vals[0] = psql.Raw("DEFAULT")
		} else {
			vals[0] = psql.Arg(s.ID)
		}

		if s.Content.IsUnset() {
			vals[1] = psql.Raw("DEFAULT")
		} else {
			vals[1] = psql.Arg(s.Content)
		}

		if s.ContentState.IsUnset() {
			vals[2] = psql.Raw("DEFAULT")
		} else {
			vals[2] = psql.Arg(s.ContentState)
		}

		if s.BookID.IsUnset() {
			vals[3] = psql.Raw("DEFAULT")
		} else {
			vals[3] = psql.Arg(s.BookID)
		}

		if s.CreatedAt.IsUnset() {
			vals[4] = psql.Raw("DEFAULT")
		} else {
			vals[4] = psql.Arg(s.CreatedAt)
		}

		if s.UpdatedAt.IsUnset() {
			vals[5] = psql.Raw("DEFAULT")
		} else {
			vals[5] = psql.Arg(s.UpdatedAt)
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s RandokuMemoSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s RandokuMemoSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 6)

	if !s.ID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if !s.Content.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "content")...),
			psql.Arg(s.Content),
		}})
	}

	if !s.ContentState.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "content_state")...),
			psql.Arg(s.ContentState),
		}})
	}

	if !s.BookID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "book_id")...),
			psql.Arg(s.BookID),
		}})
	}

	if !s.CreatedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if !s.UpdatedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindRandokuMemo retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindRandokuMemo(ctx context.Context, exec bob.Executor, IDPK int64, cols ...string) (*RandokuMemo, error) {
	if len(cols) == 0 {
		return RandokuMemos.Query(
			SelectWhere.RandokuMemos.ID.EQ(IDPK),
		).One(ctx, exec)
	}

	return RandokuMemos.Query(
		SelectWhere.RandokuMemos.ID.EQ(IDPK),
		sm.Columns(RandokuMemos.Columns().Only(cols...)),
	).One(ctx, exec)
}

// RandokuMemoExists checks the presence of a single record by primary key
func RandokuMemoExists(ctx context.Context, exec bob.Executor, IDPK int64) (bool, error) {
	return RandokuMemos.Query(
		SelectWhere.RandokuMemos.ID.EQ(IDPK),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after RandokuMemo is retrieved from the database
func (o *RandokuMemo) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = RandokuMemos.AfterSelectHooks.RunHooks(ctx, exec, RandokuMemoSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = RandokuMemos.AfterInsertHooks.RunHooks(ctx, exec, RandokuMemoSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = RandokuMemos.AfterUpdateHooks.RunHooks(ctx, exec, RandokuMemoSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = RandokuMemos.AfterDeleteHooks.RunHooks(ctx, exec, RandokuMemoSlice{o})
	}

	return err
}

// PrimaryKeyVals returns the primary key values of the RandokuMemo
func (o *RandokuMemo) PrimaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *RandokuMemo) pkEQ() dialect.Expression {
	return psql.Quote("randoku_memos", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.PrimaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the RandokuMemo
func (o *RandokuMemo) Update(ctx context.Context, exec bob.Executor, s *RandokuMemoSetter) error {
	v, err := RandokuMemos.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single RandokuMemo record with an executor
func (o *RandokuMemo) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := RandokuMemos.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the RandokuMemo using the executor
func (o *RandokuMemo) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := RandokuMemos.Query(
		SelectWhere.RandokuMemos.ID.EQ(o.ID),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after RandokuMemoSlice is retrieved from the database
func (o RandokuMemoSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = RandokuMemos.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = RandokuMemos.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = RandokuMemos.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = RandokuMemos.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o RandokuMemoSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("randoku_memos", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.PrimaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o RandokuMemoSlice) copyMatchingRows(from ...*RandokuMemo) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o RandokuMemoSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return RandokuMemos.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *RandokuMemo:
				o.copyMatchingRows(retrieved)
			case []*RandokuMemo:
				o.copyMatchingRows(retrieved...)
			case RandokuMemoSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a RandokuMemo or a slice of RandokuMemo
				// then run the AfterUpdateHooks on the slice
				_, err = RandokuMemos.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o RandokuMemoSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return RandokuMemos.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *RandokuMemo:
				o.copyMatchingRows(retrieved)
			case []*RandokuMemo:
				o.copyMatchingRows(retrieved...)
			case RandokuMemoSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a RandokuMemo or a slice of RandokuMemo
				// then run the AfterDeleteHooks on the slice
				_, err = RandokuMemos.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o RandokuMemoSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals RandokuMemoSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := RandokuMemos.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o RandokuMemoSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := RandokuMemos.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o RandokuMemoSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := RandokuMemos.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type randokuMemoJoins[Q dialect.Joinable] struct {
	typ  string
	Book func(context.Context) modAs[Q, bookColumns]
}

func (j randokuMemoJoins[Q]) aliasedAs(alias string) randokuMemoJoins[Q] {
	return buildRandokuMemoJoins[Q](buildRandokuMemoColumns(alias), j.typ)
}

func buildRandokuMemoJoins[Q dialect.Joinable](cols randokuMemoColumns, typ string) randokuMemoJoins[Q] {
	return randokuMemoJoins[Q]{
		typ:  typ,
		Book: randokuMemosJoinBook[Q](cols, typ),
	}
}

func randokuMemosJoinBook[Q dialect.Joinable](from randokuMemoColumns, typ string) func(context.Context) modAs[Q, bookColumns] {
	return func(ctx context.Context) modAs[Q, bookColumns] {
		return modAs[Q, bookColumns]{
			c: BookColumns,
			f: func(to bookColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Books.Name().As(to.Alias())).On(
						to.ID.EQ(from.BookID),
					))
				}

				return mods
			},
		}
	}
}

// Book starts a query for related objects on books
func (o *RandokuMemo) Book(mods ...bob.Mod[*dialect.SelectQuery]) BooksQuery {
	return Books.Query(append(mods,
		sm.Where(BookColumns.ID.EQ(psql.Arg(o.BookID))),
	)...)
}

func (os RandokuMemoSlice) Book(mods ...bob.Mod[*dialect.SelectQuery]) BooksQuery {
	PKArgs := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgs[i] = psql.ArgGroup(o.BookID)
	}

	return Books.Query(append(mods,
		sm.Where(psql.Group(BookColumns.ID).In(PKArgs...)),
	)...)
}

func (o *RandokuMemo) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Book":
		rel, ok := retrieved.(*Book)
		if !ok {
			return fmt.Errorf("randokuMemo cannot load %T as %q", retrieved, name)
		}

		o.R.Book = rel

		if rel != nil {
			rel.R.RandokuMemos = RandokuMemoSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("randokuMemo has no relationship %q", name)
	}
}

func PreloadRandokuMemoBook(opts ...psql.PreloadOption) psql.Preloader {
	return psql.Preload[*Book, BookSlice](orm.Relationship{
		Name: "Book",
		Sides: []orm.RelSide{
			{
				From: TableNames.RandokuMemos,
				To:   TableNames.Books,
				FromColumns: []string{
					ColumnNames.RandokuMemos.BookID,
				},
				ToColumns: []string{
					ColumnNames.Books.ID,
				},
			},
		},
	}, Books.Columns().Names(), opts...)
}

func ThenLoadRandokuMemoBook(queryMods ...bob.Mod[*dialect.SelectQuery]) psql.Loader {
	return psql.Loader(func(ctx context.Context, exec bob.Executor, retrieved any) error {
		loader, isLoader := retrieved.(interface {
			LoadRandokuMemoBook(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
		})
		if !isLoader {
			return fmt.Errorf("object %T cannot load RandokuMemoBook", retrieved)
		}

		err := loader.LoadRandokuMemoBook(ctx, exec, queryMods...)

		// Don't cause an issue due to missing relationships
		if errors.Is(err, sql.ErrNoRows) {
			return nil
		}

		return err
	})
}

// LoadRandokuMemoBook loads the randokuMemo's Book into the .R struct
func (o *RandokuMemo) LoadRandokuMemoBook(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Book = nil

	related, err := o.Book(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.RandokuMemos = RandokuMemoSlice{o}

	o.R.Book = related
	return nil
}

// LoadRandokuMemoBook loads the randokuMemo's Book into the .R struct
func (os RandokuMemoSlice) LoadRandokuMemoBook(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	books, err := os.Book(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		for _, rel := range books {
			if o.BookID.GetOrZero() != rel.ID {
				continue
			}

			rel.R.RandokuMemos = append(rel.R.RandokuMemos, o)

			o.R.Book = rel
			break
		}
	}

	return nil
}

func attachRandokuMemoBook0(ctx context.Context, exec bob.Executor, count int, randokuMemo0 *RandokuMemo, book1 *Book) (*RandokuMemo, error) {
	setter := &RandokuMemoSetter{
		BookID: omitnull.From(book1.ID),
	}

	err := randokuMemo0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachRandokuMemoBook0: %w", err)
	}

	return randokuMemo0, nil
}

func (randokuMemo0 *RandokuMemo) InsertBook(ctx context.Context, exec bob.Executor, related *BookSetter) error {
	book1, err := Books.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachRandokuMemoBook0(ctx, exec, 1, randokuMemo0, book1)
	if err != nil {
		return err
	}

	randokuMemo0.R.Book = book1

	book1.R.RandokuMemos = append(book1.R.RandokuMemos, randokuMemo0)

	return nil
}

func (randokuMemo0 *RandokuMemo) AttachBook(ctx context.Context, exec bob.Executor, book1 *Book) error {
	var err error

	_, err = attachRandokuMemoBook0(ctx, exec, 1, randokuMemo0, book1)
	if err != nil {
		return err
	}

	randokuMemo0.R.Book = book1

	book1.R.RandokuMemos = append(book1.R.RandokuMemos, randokuMemo0)

	return nil
}
