// Code generated by BobGen psql v0.38.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/jaswdr/faker/v2"
	models "github.com/sandonemaki/my_read_memo_Go_API/backend/pkg/dbmodels"
	"github.com/stephenafamo/bob"
)

type SeidokuMemoMod interface {
	Apply(context.Context, *SeidokuMemoTemplate)
}

type SeidokuMemoModFunc func(context.Context, *SeidokuMemoTemplate)

func (f SeidokuMemoModFunc) Apply(ctx context.Context, n *SeidokuMemoTemplate) {
	f(ctx, n)
}

type SeidokuMemoModSlice []SeidokuMemoMod

func (mods SeidokuMemoModSlice) Apply(ctx context.Context, n *SeidokuMemoTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// SeidokuMemoTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type SeidokuMemoTemplate struct {
	ID           func() int64
	MasterBookID func() int64
	Content      func() string
	ContentTag   func() int32
	CreatedAt    func() time.Time
	UpdatedAt    func() time.Time

	r seidokuMemoR
	f *Factory
}

type seidokuMemoR struct {
	MasterBook *seidokuMemoRMasterBookR
}

type seidokuMemoRMasterBookR struct {
	o *MasterBookTemplate
}

// Apply mods to the SeidokuMemoTemplate
func (o *SeidokuMemoTemplate) Apply(ctx context.Context, mods ...SeidokuMemoMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.SeidokuMemo
// according to the relationships in the template. Nothing is inserted into the db
func (t SeidokuMemoTemplate) setModelRels(o *models.SeidokuMemo) {
	if t.r.MasterBook != nil {
		rel := t.r.MasterBook.o.Build()
		rel.R.SeidokuMemos = append(rel.R.SeidokuMemos, o)
		o.MasterBookID = rel.ID // h2
		o.R.MasterBook = rel
	}
}

// BuildSetter returns an *models.SeidokuMemoSetter
// this does nothing with the relationship templates
func (o SeidokuMemoTemplate) BuildSetter() *models.SeidokuMemoSetter {
	m := &models.SeidokuMemoSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = &val
	}
	if o.MasterBookID != nil {
		val := o.MasterBookID()
		m.MasterBookID = &val
	}
	if o.Content != nil {
		val := o.Content()
		m.Content = &val
	}
	if o.ContentTag != nil {
		val := o.ContentTag()
		m.ContentTag = &val
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = &val
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = &val
	}

	return m
}

// BuildManySetter returns an []*models.SeidokuMemoSetter
// this does nothing with the relationship templates
func (o SeidokuMemoTemplate) BuildManySetter(number int) []*models.SeidokuMemoSetter {
	m := make([]*models.SeidokuMemoSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.SeidokuMemo
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use SeidokuMemoTemplate.Create
func (o SeidokuMemoTemplate) Build() *models.SeidokuMemo {
	m := &models.SeidokuMemo{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.MasterBookID != nil {
		m.MasterBookID = o.MasterBookID()
	}
	if o.Content != nil {
		m.Content = o.Content()
	}
	if o.ContentTag != nil {
		m.ContentTag = o.ContentTag()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.SeidokuMemoSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use SeidokuMemoTemplate.CreateMany
func (o SeidokuMemoTemplate) BuildMany(number int) models.SeidokuMemoSlice {
	m := make(models.SeidokuMemoSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableSeidokuMemo(m *models.SeidokuMemoSetter) {
	if m.MasterBookID == nil {
		val := random_int64(nil)
		m.MasterBookID = &val
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.SeidokuMemo
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *SeidokuMemoTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.SeidokuMemo) (context.Context, error) {
	var err error

	return ctx, err
}

// Create builds a seidokuMemo and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *SeidokuMemoTemplate) Create(ctx context.Context, exec bob.Executor) (*models.SeidokuMemo, error) {
	_, m, err := o.create(ctx, exec)
	return m, err
}

// MustCreate builds a seidokuMemo and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *SeidokuMemoTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.SeidokuMemo {
	_, m, err := o.create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a seidokuMemo and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *SeidokuMemoTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.SeidokuMemo {
	tb.Helper()
	_, m, err := o.create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// create builds a seidokuMemo and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// this returns a context that includes the newly inserted model
func (o *SeidokuMemoTemplate) create(ctx context.Context, exec bob.Executor) (context.Context, *models.SeidokuMemo, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableSeidokuMemo(opt)

	if o.r.MasterBook == nil {
		SeidokuMemoMods.WithNewMasterBook().Apply(ctx, o)
	}

	rel0, ok := masterBookCtx.Value(ctx)
	if !ok {
		ctx, rel0, err = o.r.MasterBook.o.create(ctx, exec)
		if err != nil {
			return ctx, nil, err
		}
	}

	opt.MasterBookID = &rel0.ID

	m, err := models.SeidokuMemos.Insert(opt).One(ctx, exec)
	if err != nil {
		return ctx, nil, err
	}
	ctx = seidokuMemoCtx.WithValue(ctx, m)

	m.R.MasterBook = rel0

	ctx, err = o.insertOptRels(ctx, exec, m)
	return ctx, m, err
}

// CreateMany builds multiple seidokuMemos and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o SeidokuMemoTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.SeidokuMemoSlice, error) {
	_, m, err := o.createMany(ctx, exec, number)
	return m, err
}

// MustCreateMany builds multiple seidokuMemos and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o SeidokuMemoTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.SeidokuMemoSlice {
	_, m, err := o.createMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple seidokuMemos and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o SeidokuMemoTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.SeidokuMemoSlice {
	tb.Helper()
	_, m, err := o.createMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// createMany builds multiple seidokuMemos and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// this returns a context that includes the newly inserted models
func (o SeidokuMemoTemplate) createMany(ctx context.Context, exec bob.Executor, number int) (context.Context, models.SeidokuMemoSlice, error) {
	var err error
	m := make(models.SeidokuMemoSlice, number)

	for i := range m {
		ctx, m[i], err = o.create(ctx, exec)
		if err != nil {
			return ctx, nil, err
		}
	}

	return ctx, m, nil
}

// SeidokuMemo has methods that act as mods for the SeidokuMemoTemplate
var SeidokuMemoMods seidokuMemoMods

type seidokuMemoMods struct{}

func (m seidokuMemoMods) RandomizeAllColumns(f *faker.Faker) SeidokuMemoMod {
	return SeidokuMemoModSlice{
		SeidokuMemoMods.RandomID(f),
		SeidokuMemoMods.RandomMasterBookID(f),
		SeidokuMemoMods.RandomContent(f),
		SeidokuMemoMods.RandomContentTag(f),
		SeidokuMemoMods.RandomCreatedAt(f),
		SeidokuMemoMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m seidokuMemoMods) ID(val int64) SeidokuMemoMod {
	return SeidokuMemoModFunc(func(_ context.Context, o *SeidokuMemoTemplate) {
		o.ID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m seidokuMemoMods) IDFunc(f func() int64) SeidokuMemoMod {
	return SeidokuMemoModFunc(func(_ context.Context, o *SeidokuMemoTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m seidokuMemoMods) UnsetID() SeidokuMemoMod {
	return SeidokuMemoModFunc(func(_ context.Context, o *SeidokuMemoTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m seidokuMemoMods) RandomID(f *faker.Faker) SeidokuMemoMod {
	return SeidokuMemoModFunc(func(_ context.Context, o *SeidokuMemoTemplate) {
		o.ID = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m seidokuMemoMods) MasterBookID(val int64) SeidokuMemoMod {
	return SeidokuMemoModFunc(func(_ context.Context, o *SeidokuMemoTemplate) {
		o.MasterBookID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m seidokuMemoMods) MasterBookIDFunc(f func() int64) SeidokuMemoMod {
	return SeidokuMemoModFunc(func(_ context.Context, o *SeidokuMemoTemplate) {
		o.MasterBookID = f
	})
}

// Clear any values for the column
func (m seidokuMemoMods) UnsetMasterBookID() SeidokuMemoMod {
	return SeidokuMemoModFunc(func(_ context.Context, o *SeidokuMemoTemplate) {
		o.MasterBookID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m seidokuMemoMods) RandomMasterBookID(f *faker.Faker) SeidokuMemoMod {
	return SeidokuMemoModFunc(func(_ context.Context, o *SeidokuMemoTemplate) {
		o.MasterBookID = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m seidokuMemoMods) Content(val string) SeidokuMemoMod {
	return SeidokuMemoModFunc(func(_ context.Context, o *SeidokuMemoTemplate) {
		o.Content = func() string { return val }
	})
}

// Set the Column from the function
func (m seidokuMemoMods) ContentFunc(f func() string) SeidokuMemoMod {
	return SeidokuMemoModFunc(func(_ context.Context, o *SeidokuMemoTemplate) {
		o.Content = f
	})
}

// Clear any values for the column
func (m seidokuMemoMods) UnsetContent() SeidokuMemoMod {
	return SeidokuMemoModFunc(func(_ context.Context, o *SeidokuMemoTemplate) {
		o.Content = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m seidokuMemoMods) RandomContent(f *faker.Faker) SeidokuMemoMod {
	return SeidokuMemoModFunc(func(_ context.Context, o *SeidokuMemoTemplate) {
		o.Content = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m seidokuMemoMods) ContentTag(val int32) SeidokuMemoMod {
	return SeidokuMemoModFunc(func(_ context.Context, o *SeidokuMemoTemplate) {
		o.ContentTag = func() int32 { return val }
	})
}

// Set the Column from the function
func (m seidokuMemoMods) ContentTagFunc(f func() int32) SeidokuMemoMod {
	return SeidokuMemoModFunc(func(_ context.Context, o *SeidokuMemoTemplate) {
		o.ContentTag = f
	})
}

// Clear any values for the column
func (m seidokuMemoMods) UnsetContentTag() SeidokuMemoMod {
	return SeidokuMemoModFunc(func(_ context.Context, o *SeidokuMemoTemplate) {
		o.ContentTag = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m seidokuMemoMods) RandomContentTag(f *faker.Faker) SeidokuMemoMod {
	return SeidokuMemoModFunc(func(_ context.Context, o *SeidokuMemoTemplate) {
		o.ContentTag = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m seidokuMemoMods) CreatedAt(val time.Time) SeidokuMemoMod {
	return SeidokuMemoModFunc(func(_ context.Context, o *SeidokuMemoTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m seidokuMemoMods) CreatedAtFunc(f func() time.Time) SeidokuMemoMod {
	return SeidokuMemoModFunc(func(_ context.Context, o *SeidokuMemoTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m seidokuMemoMods) UnsetCreatedAt() SeidokuMemoMod {
	return SeidokuMemoModFunc(func(_ context.Context, o *SeidokuMemoTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m seidokuMemoMods) RandomCreatedAt(f *faker.Faker) SeidokuMemoMod {
	return SeidokuMemoModFunc(func(_ context.Context, o *SeidokuMemoTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m seidokuMemoMods) UpdatedAt(val time.Time) SeidokuMemoMod {
	return SeidokuMemoModFunc(func(_ context.Context, o *SeidokuMemoTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m seidokuMemoMods) UpdatedAtFunc(f func() time.Time) SeidokuMemoMod {
	return SeidokuMemoModFunc(func(_ context.Context, o *SeidokuMemoTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m seidokuMemoMods) UnsetUpdatedAt() SeidokuMemoMod {
	return SeidokuMemoModFunc(func(_ context.Context, o *SeidokuMemoTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m seidokuMemoMods) RandomUpdatedAt(f *faker.Faker) SeidokuMemoMod {
	return SeidokuMemoModFunc(func(_ context.Context, o *SeidokuMemoTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m seidokuMemoMods) WithParentsCascading() SeidokuMemoMod {
	return SeidokuMemoModFunc(func(ctx context.Context, o *SeidokuMemoTemplate) {
		if isDone, _ := seidokuMemoWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = seidokuMemoWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewMasterBook(ctx, MasterBookMods.WithParentsCascading())
			m.WithMasterBook(related).Apply(ctx, o)
		}
	})
}

func (m seidokuMemoMods) WithMasterBook(rel *MasterBookTemplate) SeidokuMemoMod {
	return SeidokuMemoModFunc(func(ctx context.Context, o *SeidokuMemoTemplate) {
		o.r.MasterBook = &seidokuMemoRMasterBookR{
			o: rel,
		}
	})
}

func (m seidokuMemoMods) WithNewMasterBook(mods ...MasterBookMod) SeidokuMemoMod {
	return SeidokuMemoModFunc(func(ctx context.Context, o *SeidokuMemoTemplate) {
		related := o.f.NewMasterBook(ctx, mods...)

		m.WithMasterBook(related).Apply(ctx, o)
	})
}

func (m seidokuMemoMods) WithoutMasterBook() SeidokuMemoMod {
	return SeidokuMemoModFunc(func(ctx context.Context, o *SeidokuMemoTemplate) {
		o.r.MasterBook = nil
	})
}
