// Code generated by BobGen psql v0.38.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/jaswdr/faker/v2"
	models "github.com/sandonemaki/my_read_memo_Go_API/backend/cmd/core/pkg/dbmodels"
	"github.com/stephenafamo/bob"
)

type KindleHighlightMod interface {
	Apply(context.Context, *KindleHighlightTemplate)
}

type KindleHighlightModFunc func(context.Context, *KindleHighlightTemplate)

func (f KindleHighlightModFunc) Apply(ctx context.Context, n *KindleHighlightTemplate) {
	f(ctx, n)
}

type KindleHighlightModSlice []KindleHighlightMod

func (mods KindleHighlightModSlice) Apply(ctx context.Context, n *KindleHighlightTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// KindleHighlightTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type KindleHighlightTemplate struct {
	ID           func() int64
	MasterBookID func() int64
	Position     func() int32
	Highlight    func() string
	Memo         func() string
	LastSyncedAt func() time.Time
	CreatedAt    func() time.Time
	UpdatedAt    func() time.Time

	r kindleHighlightR
	f *Factory
}

type kindleHighlightR struct {
	MasterBook *kindleHighlightRMasterBookR
}

type kindleHighlightRMasterBookR struct {
	o *MasterBookTemplate
}

// Apply mods to the KindleHighlightTemplate
func (o *KindleHighlightTemplate) Apply(ctx context.Context, mods ...KindleHighlightMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.KindleHighlight
// according to the relationships in the template. Nothing is inserted into the db
func (t KindleHighlightTemplate) setModelRels(o *models.KindleHighlight) {
	if t.r.MasterBook != nil {
		rel := t.r.MasterBook.o.Build()
		rel.R.KindleHighlights = append(rel.R.KindleHighlights, o)
		o.MasterBookID = rel.ID // h2
		o.R.MasterBook = rel
	}
}

// BuildSetter returns an *models.KindleHighlightSetter
// this does nothing with the relationship templates
func (o KindleHighlightTemplate) BuildSetter() *models.KindleHighlightSetter {
	m := &models.KindleHighlightSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = &val
	}
	if o.MasterBookID != nil {
		val := o.MasterBookID()
		m.MasterBookID = &val
	}
	if o.Position != nil {
		val := o.Position()
		m.Position = &val
	}
	if o.Highlight != nil {
		val := o.Highlight()
		m.Highlight = &val
	}
	if o.Memo != nil {
		val := o.Memo()
		m.Memo = &val
	}
	if o.LastSyncedAt != nil {
		val := o.LastSyncedAt()
		m.LastSyncedAt = &val
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = &val
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = &val
	}

	return m
}

// BuildManySetter returns an []*models.KindleHighlightSetter
// this does nothing with the relationship templates
func (o KindleHighlightTemplate) BuildManySetter(number int) []*models.KindleHighlightSetter {
	m := make([]*models.KindleHighlightSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.KindleHighlight
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use KindleHighlightTemplate.Create
func (o KindleHighlightTemplate) Build() *models.KindleHighlight {
	m := &models.KindleHighlight{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.MasterBookID != nil {
		m.MasterBookID = o.MasterBookID()
	}
	if o.Position != nil {
		m.Position = o.Position()
	}
	if o.Highlight != nil {
		m.Highlight = o.Highlight()
	}
	if o.Memo != nil {
		m.Memo = o.Memo()
	}
	if o.LastSyncedAt != nil {
		m.LastSyncedAt = o.LastSyncedAt()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.KindleHighlightSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use KindleHighlightTemplate.CreateMany
func (o KindleHighlightTemplate) BuildMany(number int) models.KindleHighlightSlice {
	m := make(models.KindleHighlightSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableKindleHighlight(m *models.KindleHighlightSetter) {
	if m.MasterBookID == nil {
		val := random_int64(nil)
		m.MasterBookID = &val
	}
	if m.LastSyncedAt == nil {
		val := random_time_Time(nil)
		m.LastSyncedAt = &val
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.KindleHighlight
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *KindleHighlightTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.KindleHighlight) (context.Context, error) {
	var err error

	return ctx, err
}

// Create builds a kindleHighlight and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *KindleHighlightTemplate) Create(ctx context.Context, exec bob.Executor) (*models.KindleHighlight, error) {
	_, m, err := o.create(ctx, exec)
	return m, err
}

// MustCreate builds a kindleHighlight and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *KindleHighlightTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.KindleHighlight {
	_, m, err := o.create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a kindleHighlight and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *KindleHighlightTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.KindleHighlight {
	tb.Helper()
	_, m, err := o.create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// create builds a kindleHighlight and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// this returns a context that includes the newly inserted model
func (o *KindleHighlightTemplate) create(ctx context.Context, exec bob.Executor) (context.Context, *models.KindleHighlight, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableKindleHighlight(opt)

	if o.r.MasterBook == nil {
		KindleHighlightMods.WithNewMasterBook().Apply(ctx, o)
	}

	rel0, ok := masterBookCtx.Value(ctx)
	if !ok {
		ctx, rel0, err = o.r.MasterBook.o.create(ctx, exec)
		if err != nil {
			return ctx, nil, err
		}
	}

	opt.MasterBookID = &rel0.ID

	m, err := models.KindleHighlights.Insert(opt).One(ctx, exec)
	if err != nil {
		return ctx, nil, err
	}
	ctx = kindleHighlightCtx.WithValue(ctx, m)

	m.R.MasterBook = rel0

	ctx, err = o.insertOptRels(ctx, exec, m)
	return ctx, m, err
}

// CreateMany builds multiple kindleHighlights and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o KindleHighlightTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.KindleHighlightSlice, error) {
	_, m, err := o.createMany(ctx, exec, number)
	return m, err
}

// MustCreateMany builds multiple kindleHighlights and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o KindleHighlightTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.KindleHighlightSlice {
	_, m, err := o.createMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple kindleHighlights and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o KindleHighlightTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.KindleHighlightSlice {
	tb.Helper()
	_, m, err := o.createMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// createMany builds multiple kindleHighlights and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// this returns a context that includes the newly inserted models
func (o KindleHighlightTemplate) createMany(ctx context.Context, exec bob.Executor, number int) (context.Context, models.KindleHighlightSlice, error) {
	var err error
	m := make(models.KindleHighlightSlice, number)

	for i := range m {
		ctx, m[i], err = o.create(ctx, exec)
		if err != nil {
			return ctx, nil, err
		}
	}

	return ctx, m, nil
}

// KindleHighlight has methods that act as mods for the KindleHighlightTemplate
var KindleHighlightMods kindleHighlightMods

type kindleHighlightMods struct{}

func (m kindleHighlightMods) RandomizeAllColumns(f *faker.Faker) KindleHighlightMod {
	return KindleHighlightModSlice{
		KindleHighlightMods.RandomID(f),
		KindleHighlightMods.RandomMasterBookID(f),
		KindleHighlightMods.RandomPosition(f),
		KindleHighlightMods.RandomHighlight(f),
		KindleHighlightMods.RandomMemo(f),
		KindleHighlightMods.RandomLastSyncedAt(f),
		KindleHighlightMods.RandomCreatedAt(f),
		KindleHighlightMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m kindleHighlightMods) ID(val int64) KindleHighlightMod {
	return KindleHighlightModFunc(func(_ context.Context, o *KindleHighlightTemplate) {
		o.ID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m kindleHighlightMods) IDFunc(f func() int64) KindleHighlightMod {
	return KindleHighlightModFunc(func(_ context.Context, o *KindleHighlightTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m kindleHighlightMods) UnsetID() KindleHighlightMod {
	return KindleHighlightModFunc(func(_ context.Context, o *KindleHighlightTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m kindleHighlightMods) RandomID(f *faker.Faker) KindleHighlightMod {
	return KindleHighlightModFunc(func(_ context.Context, o *KindleHighlightTemplate) {
		o.ID = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m kindleHighlightMods) MasterBookID(val int64) KindleHighlightMod {
	return KindleHighlightModFunc(func(_ context.Context, o *KindleHighlightTemplate) {
		o.MasterBookID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m kindleHighlightMods) MasterBookIDFunc(f func() int64) KindleHighlightMod {
	return KindleHighlightModFunc(func(_ context.Context, o *KindleHighlightTemplate) {
		o.MasterBookID = f
	})
}

// Clear any values for the column
func (m kindleHighlightMods) UnsetMasterBookID() KindleHighlightMod {
	return KindleHighlightModFunc(func(_ context.Context, o *KindleHighlightTemplate) {
		o.MasterBookID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m kindleHighlightMods) RandomMasterBookID(f *faker.Faker) KindleHighlightMod {
	return KindleHighlightModFunc(func(_ context.Context, o *KindleHighlightTemplate) {
		o.MasterBookID = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m kindleHighlightMods) Position(val int32) KindleHighlightMod {
	return KindleHighlightModFunc(func(_ context.Context, o *KindleHighlightTemplate) {
		o.Position = func() int32 { return val }
	})
}

// Set the Column from the function
func (m kindleHighlightMods) PositionFunc(f func() int32) KindleHighlightMod {
	return KindleHighlightModFunc(func(_ context.Context, o *KindleHighlightTemplate) {
		o.Position = f
	})
}

// Clear any values for the column
func (m kindleHighlightMods) UnsetPosition() KindleHighlightMod {
	return KindleHighlightModFunc(func(_ context.Context, o *KindleHighlightTemplate) {
		o.Position = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m kindleHighlightMods) RandomPosition(f *faker.Faker) KindleHighlightMod {
	return KindleHighlightModFunc(func(_ context.Context, o *KindleHighlightTemplate) {
		o.Position = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m kindleHighlightMods) Highlight(val string) KindleHighlightMod {
	return KindleHighlightModFunc(func(_ context.Context, o *KindleHighlightTemplate) {
		o.Highlight = func() string { return val }
	})
}

// Set the Column from the function
func (m kindleHighlightMods) HighlightFunc(f func() string) KindleHighlightMod {
	return KindleHighlightModFunc(func(_ context.Context, o *KindleHighlightTemplate) {
		o.Highlight = f
	})
}

// Clear any values for the column
func (m kindleHighlightMods) UnsetHighlight() KindleHighlightMod {
	return KindleHighlightModFunc(func(_ context.Context, o *KindleHighlightTemplate) {
		o.Highlight = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m kindleHighlightMods) RandomHighlight(f *faker.Faker) KindleHighlightMod {
	return KindleHighlightModFunc(func(_ context.Context, o *KindleHighlightTemplate) {
		o.Highlight = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m kindleHighlightMods) Memo(val string) KindleHighlightMod {
	return KindleHighlightModFunc(func(_ context.Context, o *KindleHighlightTemplate) {
		o.Memo = func() string { return val }
	})
}

// Set the Column from the function
func (m kindleHighlightMods) MemoFunc(f func() string) KindleHighlightMod {
	return KindleHighlightModFunc(func(_ context.Context, o *KindleHighlightTemplate) {
		o.Memo = f
	})
}

// Clear any values for the column
func (m kindleHighlightMods) UnsetMemo() KindleHighlightMod {
	return KindleHighlightModFunc(func(_ context.Context, o *KindleHighlightTemplate) {
		o.Memo = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m kindleHighlightMods) RandomMemo(f *faker.Faker) KindleHighlightMod {
	return KindleHighlightModFunc(func(_ context.Context, o *KindleHighlightTemplate) {
		o.Memo = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m kindleHighlightMods) LastSyncedAt(val time.Time) KindleHighlightMod {
	return KindleHighlightModFunc(func(_ context.Context, o *KindleHighlightTemplate) {
		o.LastSyncedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m kindleHighlightMods) LastSyncedAtFunc(f func() time.Time) KindleHighlightMod {
	return KindleHighlightModFunc(func(_ context.Context, o *KindleHighlightTemplate) {
		o.LastSyncedAt = f
	})
}

// Clear any values for the column
func (m kindleHighlightMods) UnsetLastSyncedAt() KindleHighlightMod {
	return KindleHighlightModFunc(func(_ context.Context, o *KindleHighlightTemplate) {
		o.LastSyncedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m kindleHighlightMods) RandomLastSyncedAt(f *faker.Faker) KindleHighlightMod {
	return KindleHighlightModFunc(func(_ context.Context, o *KindleHighlightTemplate) {
		o.LastSyncedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m kindleHighlightMods) CreatedAt(val time.Time) KindleHighlightMod {
	return KindleHighlightModFunc(func(_ context.Context, o *KindleHighlightTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m kindleHighlightMods) CreatedAtFunc(f func() time.Time) KindleHighlightMod {
	return KindleHighlightModFunc(func(_ context.Context, o *KindleHighlightTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m kindleHighlightMods) UnsetCreatedAt() KindleHighlightMod {
	return KindleHighlightModFunc(func(_ context.Context, o *KindleHighlightTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m kindleHighlightMods) RandomCreatedAt(f *faker.Faker) KindleHighlightMod {
	return KindleHighlightModFunc(func(_ context.Context, o *KindleHighlightTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m kindleHighlightMods) UpdatedAt(val time.Time) KindleHighlightMod {
	return KindleHighlightModFunc(func(_ context.Context, o *KindleHighlightTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m kindleHighlightMods) UpdatedAtFunc(f func() time.Time) KindleHighlightMod {
	return KindleHighlightModFunc(func(_ context.Context, o *KindleHighlightTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m kindleHighlightMods) UnsetUpdatedAt() KindleHighlightMod {
	return KindleHighlightModFunc(func(_ context.Context, o *KindleHighlightTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m kindleHighlightMods) RandomUpdatedAt(f *faker.Faker) KindleHighlightMod {
	return KindleHighlightModFunc(func(_ context.Context, o *KindleHighlightTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m kindleHighlightMods) WithParentsCascading() KindleHighlightMod {
	return KindleHighlightModFunc(func(ctx context.Context, o *KindleHighlightTemplate) {
		if isDone, _ := kindleHighlightWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = kindleHighlightWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewMasterBook(ctx, MasterBookMods.WithParentsCascading())
			m.WithMasterBook(related).Apply(ctx, o)
		}
	})
}

func (m kindleHighlightMods) WithMasterBook(rel *MasterBookTemplate) KindleHighlightMod {
	return KindleHighlightModFunc(func(ctx context.Context, o *KindleHighlightTemplate) {
		o.r.MasterBook = &kindleHighlightRMasterBookR{
			o: rel,
		}
	})
}

func (m kindleHighlightMods) WithNewMasterBook(mods ...MasterBookMod) KindleHighlightMod {
	return KindleHighlightModFunc(func(ctx context.Context, o *KindleHighlightTemplate) {
		related := o.f.NewMasterBook(ctx, mods...)

		m.WithMasterBook(related).Apply(ctx, o)
	})
}

func (m kindleHighlightMods) WithoutMasterBook() KindleHighlightMod {
	return KindleHighlightModFunc(func(ctx context.Context, o *KindleHighlightTemplate) {
		o.r.MasterBook = nil
	})
}
