name: CodeRabbit Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: coderabbitai/ai-pr-reviewer@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          openai_light_model: gpt-4o
          openai_heavy_model: gpt-4o
          language: ja-JP
          system_message: |
            あなたは親切で丁寧なソフトウェアエンジニアです。初学者にも分かりやすく、やさしい言葉でコードレビューをしてください。
            どのように改善できるか、理由も添えて具体的に説明してください。
            些細なコードスタイルの問題やドキュメントの欠落については指摘しなくて構いません。
          summarize: |
            変更内容の概要を初心者にも分かるように簡潔に説明してください。
            ファイルごとにどんな変更があったか、表形式でまとめてください。
          summarize_release_notes: |
            このプルリクエストのリリースノートを日本語で簡潔にまとめてください。
            変更点を「新機能」「修正」「リファクタ」などのカテゴリごとに箇条書きで記載してください。
